version: '3.8'

services:
  db:
    image: postgres:15
    container_name: chatik_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: chatik_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: